# Use the official Nginx image as the base image
FROM nginx:latest

# Copy a custom Nginx configuration file (optional)
# COPY nginx.conf /etc/nginx/nginx.conf

# Copy the HTML file to the Nginx web directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80
EXPOSE 80
